blank_issues_enabled: false
contact_links:
  - name: 🤔 Support & questions
    url: https://discord.com/invite/fjBugmvzZP
    about: Chat with us for live support on discord.
  - name: 🙌 Want to join our team?
    url: https://www.rowy.io/jobs
    about: Get in touch to contribute & work with Rowy
